- name: Set file directory path
  set_fact:
    role_name: "{{ role_path | basename }}"
    directory_path: "{{ stacks_src }}/{{ role_name }}"

- name: synchronize docker-compose files to server
  become_user: "{{ username }}"
  synchronize:
    src: files/
    dest: "{{ directory_path }}/"
  notify: deploy {{ role_name }}

- name: Populate config files from vault
  template:
    src: smarthomekey.json.j2
    dest: "{{directory_path}}/config/smarthomekey.json"
    mode: "0600"
  notify: deploy {{ role_name }}
