---
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - LOG_CONFS=true
      - SERVERURL=43.229.91.134
      - SERVERPORT=13185 #optional
      - PEERS=danishIphone,danishMac,doonoIphone,danishAndroid
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PEERDNS=192.168.1.8
    volumes:
      - wireguard:/config
    ports:
      - 13185:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  wireguard:
    name: wireguard_config
    external: false
