---
- name: Uninstall an application {{ app_name }} from the server
  hosts: all
  become: true
  vars:
    application_name: "{{ app_name }}"

  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: "'ansible_os_family' == 'Debian'"

    - name: Uninstall the application using the appropriate package manager
      package:
        name: "{{ application_name }}"
        state: absent
