- name: Set file directory path
  set_fact:
    role_name: "{{ role_path | basename }}"
    directory_path: "{{ stacks_src }}/{{ role_name }}"

- name: synchronize docker-compose files to server
  become_user: "{{ username }}"
  synchronize:
    src: files/
    dest: "{{ directory_path }}/"

- name: Populate .env files from vault
  template:
    src: env.j2
    dest: "{{directory_path}}/.env"
    mode: "0600"
  notify: deploy {{ role_name }}
